In [1]:
import numpy as np

In [2]:
A = np.array([[0,0,0,1,0,1,1,0,0],
              [0,0,0,1,1,0,1,0,0],
              [0,1,1,0,2,0,0,0,0],
              [1,0,0,0,0,0,0,1,1]])

In [3]:
print('DTM의 크기(shape) :', np.shape(A))

DTM의 크기(shape) : (4, 9)


In [4]:
U,s,VT = np.linalg.svd(A, full_matrices = True)

print('행렬 U :')
print(U.round(2))
print('행렬 U의 크기(shape) :',np.shape(U))

행렬 U :
[[ 0.24  0.75  0.    0.62]
 [ 0.51  0.44 -0.   -0.74]
 [ 0.83 -0.49  0.    0.27]
 [ 0.    0.    1.   -0.  ]]
행렬 U의 크기(shape) : (4, 4)


In [5]:
print('특이값 벡터 :')
print(s.round(2))
print('특이값 벡터의 크기(shape) :',np.shape(s))

특이값 벡터 :
[2.69 2.05 1.73 0.77]
특이값 벡터의 크기(shape) : (4,)


In [6]:
S = np.zeros((4, 9))

S[:4, :4] = np.diag(s)

print('대각 행렬 S :')
print(S.round(2))

print('대각 행렬의 크기(shape) :')
print(np.shape(S))

대각 행렬 S :
[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]
대각 행렬의 크기(shape) :
(4, 9)


In [7]:
print('직교행렬 VT :')
print(VT.round(2))

print('직교 행렬 VT의 크기(shape) :')
print(np.shape(VT))

직교행렬 VT :
[[ 0.    0.31  0.31  0.28  0.8   0.09  0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [-0.    0.35  0.35 -0.16 -0.25  0.8  -0.16  0.    0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]
직교 행렬 VT의 크기(shape) :
(9, 9)


In [8]:
np.dot(np.dot(U,S), VT)

array([[ 2.54185942e-16,  2.77555756e-16,  1.38777878e-16,
         1.00000000e+00,  9.71445147e-17,  1.00000000e+00,
         1.00000000e+00,  1.43925516e-16,  1.43925516e-16],
       [ 1.94348857e-16,  2.77555756e-17,  2.77555756e-17,
         1.00000000e+00,  1.00000000e+00,  5.55111512e-17,
         1.00000000e+00, -2.15888274e-16, -2.15888274e-16],
       [ 1.14194830e-16,  1.00000000e+00,  1.00000000e+00,
         2.08166817e-16,  2.00000000e+00,  3.05311332e-16,
         2.08166817e-16,  1.79906895e-16,  1.79906895e-16],
       [ 1.00000000e+00, -1.08688819e-16,  1.05985365e-16,
         3.60407161e-16, -8.32607463e-17,  1.44518887e-16,
        -2.41853764e-17,  1.00000000e+00,  1.00000000e+00]])

In [9]:
S = S[:2,:2]

print('대각 행렬 S :')
print(S.round(2))

대각 행렬 S :
[[2.69 0.  ]
 [0.   2.05]]


In [10]:
U = U[:,:2]
print('행렬 U :')
print(U.round(2))

행렬 U :
[[ 0.24  0.75]
 [ 0.51  0.44]
 [ 0.83 -0.49]
 [ 0.    0.  ]]


In [11]:
VT = VT[:2,:]
print('직교행렬 VT :')
print(VT.round(2))

직교행렬 VT :
[[ 0.    0.31  0.31  0.28  0.8   0.09  0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [12]:
A_prime = np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


In [13]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

C:\Users\USER\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [14]:
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data
print('샘플의 수 :',len(documents))

샘플의 수 : 11314


In [15]:
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [16]:
dataset.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [17]:
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [18]:
news_df = pd.DataFrame({'document':documents})

In [19]:
news_df.head(10)

document
0  Well i'm not sure about the story nad it did s...
1  \n\n\n\n\n\n\nYeah, do you expect people to re...
2  Although I realize that principle is not one o...
3  Notwithstanding all the legitimate fuss about ...
4  Well, I will have to change the scoring on my ...
5   \n \nI read somewhere, I think in Morton Smit...
6  \nOk.  I have a record that shows a IIsi with ...
7  \n\n\nSounds like wishful guessing.\n\n\n\n\n'...
8   Nobody is saying that you shouldn't be allowe...
9  \n  I was wondering if anyone can shed any lig...

In [20]:

# 특수 문자 제거
news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]", " ")
# 길이가 3이하인 단어는 제거 (길이가 짧은 단어 제거)
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower())

In [21]:
news_df['clean_doc'][1]

"yeah, expect people read faq, etc. actually accept hard atheism? need little leap faith, jimmy. your logic runs steam! jim, sorry can't pity you, jim. sorry that have these feelings denial about faith need well, just pretend that will happily ever after anyway. maybe start newsgroup, alt.atheist.hard, won't bummin' much? bye-bye, jim. don't forget your flintstone's chewables! bake timmons,"

In [22]:
# NLTK로부터 불용어를 받아온다.
stop_words = stopwords.words('english')
tokenized_doc = news_df['clean_doc'].apply(lambda x: x.split()) # 토큰화
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])
# 불용어를 제거합니다.

In [23]:
print(tokenized_doc[1])

['yeah,', 'expect', 'people', 'read', 'faq,', 'etc.', 'actually', 'accept', 'hard', 'atheism?', 'need', 'little', 'leap', 'faith,', 'jimmy.', 'logic', 'runs', 'steam!', 'jim,', 'sorry', "can't", 'pity', 'you,', 'jim.', 'sorry', 'feelings', 'denial', 'faith', 'need', 'well,', 'pretend', 'happily', 'ever', 'anyway.', 'maybe', 'start', 'newsgroup,', 'alt.atheist.hard,', "bummin'", 'much?', 'bye-bye,', 'jim.', 'forget', "flintstone's", 'chewables!', 'bake', 'timmons,']


In [24]:
vectorizer = TfidfVectorizer(stop_words='english', max_features= 1000, # 상위 1,000개의 단어를 보존 
max_df = 0.5, smooth_idf=True)

X = vectorizer.fit_transform(news_df['clean_doc'])

# TF-IDF 행렬의 크기 확인
print('TF-IDF 행렬의 크기 :',X.shape)

TF-IDF 행렬의 크기 : (11314, 1000)


In [25]:
svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_)

20

In [26]:
terms = vectorizer.get_feature_names_out() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(svd_model.components_,terms)

Topic 1: [('just', 0.20273), ('don', 0.19949), ('like', 0.19534), ('know', 0.18819), ('people', 0.17851)]
Topic 2: [('thanks', 0.31973), ('windows', 0.27738), ('card', 0.17369), ('drive', 0.15927), ('mail', 0.1488)]
Topic 3: [('game', 0.31991), ('team', 0.27972), ('year', 0.26585), ('games', 0.20684), ('drive', 0.17141)]
Topic 4: [('edu', 0.42972), ('thanks', 0.24949), ('mail', 0.17243), ('game', 0.12812), ('team', 0.12645)]
Topic 5: [('know', 0.41918), ('does', 0.305), ('thanks', 0.26133), ('don', 0.21061), ('just', 0.19501)]
Topic 6: [('drive', 0.45668), ('edu', 0.21787), ('thanks', 0.18804), ('scsi', 0.1573), ('drives', 0.12178)]
Topic 7: [('just', 0.56807), ('edu', 0.43053), ('don', 0.22492), ('like', 0.19983), ('soon', 0.09527)]
Topic 8: [('chip', 0.2163), ('government', 0.2001), ('encryption', 0.14658), ('like', 0.14639), ('clipper', 0.14265)]
Topic 9: [('don', 0.32188), ('know', 0.31942), ('edu', 0.28677), ('does', 0.26522), ('think', 0.19896)]
Topic 10: [('does', 0.47651), ('ca

In [27]:
tokenized_doc[:5]

0    [well, sure, story, seem, biased., disagree, s...
1    [yeah,, expect, people, read, faq,, etc., actu...
2    [although, realize, principle, strongest, poin...
3    [notwithstanding, legitimate, fuss, proposal,,...
4    [well,, change, scoring, playoff, pool., unfor...
Name: clean_doc, dtype: object

In [28]:
from gensim import corpora

In [29]:
dictionary = corpora.Dictionary(tokenized_doc)
corpus = [dictionary.doc2bow(text) for text in tokenized_doc]
print(corpus[1]) # 수행된 결과에서 두번째 뉴스 출력. 첫번째 문서의 인덱스는 0

[(59, 1), (60, 1), (61, 1), (62, 1), (63, 1), (64, 1), (65, 1), (66, 1), (67, 1), (68, 1), (69, 1), (70, 1), (71, 1), (72, 1), (73, 1), (74, 1), (75, 1), (76, 1), (77, 1), (78, 1), (79, 1), (80, 1), (81, 1), (82, 2), (83, 1), (84, 1), (85, 1), (86, 1), (87, 1), (88, 1), (89, 2), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 2), (97, 1), (98, 1), (99, 1), (100, 1), (101, 1), (102, 1)]


In [30]:
print(dictionary[66])

bye-bye,


In [31]:
len(dictionary)

181856

In [32]:
import gensim
NUM_TOPICS = 20 # 20개의 토픽, k=20
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = NUM_TOPICS, id2word=dictionary, passes=15)
topics = ldamodel.print_topics(num_words=4)
for topic in topics:
    print(topic)

(0, '0.015*"medical" + 0.013*"health" + 0.008*"patients" + 0.007*"water"')
(1, '0.011*"government" + 0.007*"public" + 0.005*"state" + 0.005*"president"')
(2, '0.007*"firearms" + 0.006*"guns" + 0.004*"weapon" + 0.003*"handgun"')
(3, '0.005*"from:" + 0.005*"objective" + 0.003*"os/2" + 0.003*"memory."')
(4, '0.027*"turkish" + 0.027*"armenian" + 0.016*"armenians" + 0.013*"greek"')
(5, '0.014*"jesus" + 0.009*"believe" + 0.009*"christian" + 0.008*"bible"')
(6, '0.009*"file" + 0.007*"available" + 0.006*"program" + 0.006*"using"')
(7, '0.008*"----------------------------------------------------------------------------" + 0.008*"surrender" + 0.008*"gordon" + 0.007*"banks"')
(8, '0.034*"drive" + 0.021*"disk" + 0.018*"scsi" + 0.016*"hard"')
(9, '0.010*"myers:" + 0.009*"henrik]" + 0.004*"lebanese" + 0.004*"karabakh"')
(10, '0.035*"space" + 0.011*"nasa" + 0.010*"launch" + 0.008*"55.0"')
(11, '0.008*"university" + 0.005*"excellent" + 0.004*"asking" + 0.004*"shipping"')
(12, '0.005*"nubus" + 0.003*"c

In [33]:
print(ldamodel.print_topics())

[(0, '0.015*"medical" + 0.013*"health" + 0.008*"patients" + 0.007*"water" + 0.007*"april" + 0.006*"radar" + 0.005*"newsletter" + 0.005*"disease" + 0.005*"cancer" + 0.005*"1993"'), (1, '0.011*"government" + 0.007*"public" + 0.005*"state" + 0.005*"president" + 0.005*"encryption" + 0.005*"states" + 0.005*"national" + 0.004*"israel" + 0.004*"security" + 0.004*"united"'), (2, '0.007*"firearms" + 0.006*"guns" + 0.004*"weapon" + 0.003*"handgun" + 0.003*"homicide" + 0.003*"quantum" + 0.003*"wires" + 0.003*"firearm" + 0.003*"handguns" + 0.003*"cable"'), (3, '0.005*"from:" + 0.005*"objective" + 0.003*"os/2" + 0.003*"memory." + 0.003*"date:" + 0.003*"judges" + 0.002*"swap" + 0.002*"genetic" + 0.002*"patient" + 0.002*"5.25""'), (4, '0.027*"turkish" + 0.027*"armenian" + 0.016*"armenians" + 0.013*"greek" + 0.012*"jews" + 0.012*"turkey" + 0.011*"turks" + 0.009*"----" + 0.009*"genocide" + 0.009*"armenia"'), (5, '0.014*"jesus" + 0.009*"believe" + 0.009*"christian" + 0.008*"bible" + 0.007*"christians" +

In [34]:
import pyLDAvis.gensim_models

In [35]:
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(ldamodel, corpus, dictionary)
pyLDAvis.display(vis)

In [36]:
for i, topic_list in enumerate(ldamodel[corpus]):
    if i==5:
        break
    print(i,'번째 문서의 topic 비율은',topic_list)

0 번째 문서의 topic 비율은 [(1, 0.43423152), (6, 0.03037082), (14, 0.33694622), (17, 0.18623629)]
1 번째 문서의 topic 비율은 [(5, 0.11636925), (17, 0.8616335)]
2 번째 문서의 topic 비율은 [(1, 0.459273), (14, 0.0248515), (17, 0.4834385), (18, 0.019285263)]
3 번째 문서의 topic 비율은 [(1, 0.48739505), (14, 0.029678218), (17, 0.46233174)]
4 번째 문서의 topic 비율은 [(0, 0.29811487), (6, 0.078493126), (17, 0.22735545), (18, 0.36638296)]
